server:
  error:
    include-exception: true
    include-stacktrace: always
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  rooturl: '/'

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    cache: false

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/hyedini?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true
      pool-name: hikari-cp
      maximum-pool-size: 5
      username: root
      password: 1q2w3e4r%
      driver-class-name: com.mysql.cj.jdbc.Driver
      auto-commit: false

logging:
  level:
    root: debug
    io.lettuce: warn
    org.apache.ibatis: debug
    org.springframework: warn
    org.springframework.jdbc.core:
      JdbcTemplate: debug
      StatementCreatorUtils: trace
  file:
    name: project.log
    max-size: 100MB
    path: './logs'